import "./globals.css";
import AppLayout from "@/containers/AppLayout";
import ChatProvider from "@/context/ChatContext";
import UserProvider from "@/context/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-[100vh]">
        <UserProvider>
          <ChatProvider>
            <AppLayout>
              {children}
            </AppLayout>
          </ChatProvider>
        </UserProvider>
      </body>
    </html>
  );
}
