import "./globals.css";
import AppLayout from "@/containers/AppLayout";
import UserProvider from "@/context/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-[100vh]">
        <UserProvider>
          <AppLayout>
            {children}
          </AppLayout>
        </UserProvider>
      </body>
    </html>
  );
}
